Repository hamler-lang/hamler, pull requests merged in 2020-07, with the labels that each got.

#238 stack: upgrade 'purescript' lib
  lib/System/IO/Printf.hm
  stack.yaml
Labels: enhancement

#239 feat(lib): add 'Terminate' typeclass
  lib/Control/Behaviour/Common/GenTypes.hm
  lib/Control/Behaviour/Common/Terminate.hm
  lib/Control/Behaviour/GenServer.hm
  lib/Control/Behaviour/GenServer/Types.hm
Labels: enhancement

#240 feat(lib): improve the 'Supervisor' and 'GenServer' behaviours
  lib/Control/Behaviour/Common/Types.hm
  lib/Control/Behaviour/GenServer.erl
  lib/Control/Behaviour/GenServer.hm
  lib/Control/Behaviour/GenServer/Types.hm
  lib/Control/Behaviour/Supervisor.erl
  lib/Control/Behaviour/Supervisor.hm
  lib/Control/Behaviour/Supervisor/Proxy.erl
  lib/Control/Behaviour/Supervisor/Types.hm
Labels: enhancement

#242 refactor(lib): refactor GenEvent, GenServer, and GenStatem behaviours
  lib/Control/Behaviour/GenEvent.hm
  lib/Control/Behaviour/GenEvent/Types.hm
  lib/Control/Behaviour/GenServer.erl
  lib/Control/Behaviour/GenServer.hm
  lib/Control/Behaviour/GenServer/Types.hm
  lib/Control/Behaviour/GenStatem.erl
  lib/Control/Behaviour/GenStatem.hm
  lib/Control/Behaviour/GenStatem/Types.hm
  lib/Control/Behaviour/GenTypes.hm
  lib/Control/Behaviour/Supervisor.hm
  lib/Control/Behaviour/Supervisor/Types.hm
  lib/Control/Behaviour/Terminate.hm
Labels: enhancement

#243 refactor(lib): move Demo/* to hamler-demo project
  lib/Demo/Event.hm
  lib/Demo/Server.hm
Labels: enhancement

#251 build(stack): upgrade the 'purescript' lib
  stack.yaml
Labels: enhancement

#253 refactor(ERTS): rename module Init to Boot
  lib/ERTS/Boot.erl
  lib/ERTS/Boot.hm
Labels: enhancement

#254 feat(Logger): add an experimental Logger module
  lib/System/Logger.hm
Labels: enhancement

#259 feat(Timer): add an inital Timer module
  lib/Data/Time.hm
  lib/System/Timer.erl
  lib/System/Timer.hm
Labels: enhancement

#262 refactor(GenServer): improve the GenServer behaviour
  lib/Control/Behaviour/GenServer.hm
  lib/Control/Behaviour/GenServer/Proxy.erl
  lib/Control/Behaviour/GenServer/Types.hm
Labels: enhancement

#263 refactor(lib): remove the ERTS folder, improve the structure of libs
  lib/Data/Atomics.erl
  lib/Data/Atomics.hm
  lib/Data/Counters.erl
  lib/Data/Counters.hm
  lib/Data/Term.hm
  lib/Data/Term/Persistent.hm
  lib/System/Init.erl
  lib/System/Init.hm
Labels: enhancement

#264 refactor(Foreign): improve FFI design
  lib/Foreign.erl
  lib/Foreign.hm
Labels: enhancement

#265 fix(Monad): fix wrong definition of IO monad
  lib/Control/Monad.erl
  lib/Control/Monad.hm
  lib/Prelude.hm
  lib/System/IO/Printf.erl
Labels: enhancement

#268 fix(IO): fix FFI with IO Effect
  lib/Control/Application.erl
  lib/Control/Application.hm
  lib/Control/Behaviour/GenEvent.erl
  lib/Control/Behaviour/GenServer.erl
  lib/Control/Behaviour/GenStatem.erl
  lib/Control/Behaviour/Supervisor.erl
  lib/Control/Distributed/Node.erl
  lib/Control/Distributed/RPC.erl
  lib/Control/Process.erl
  lib/Data/Atomics.erl
  lib/Data/Counters.erl
  lib/Data/Enum.erl
  lib/Data/Ref.erl
  lib/Data/Ref.hm
  lib/Data/Time.erl
  lib/Database/DETS.erl
  lib/Database/ETS.erl
  lib/Database/Mnesia.erl
  lib/Network/Socket.erl
  lib/Network/Socket.hm
  lib/Network/TCP.erl
  lib/Network/UDP.erl
  lib/System/Dir.erl
  lib/System/Env.erl
  lib/System/Error.erl
  lib/System/File.erl
  lib/System/File.hm
  lib/System/IO.erl
  lib/System/IO/Printf.erl
  lib/System/Init.erl
  lib/System/OS.erl
  lib/System/Random.erl
  lib/System/Timer.erl
  lib/System/VM.erl
Labels: enhancement

#269 fix(GenServer): fix GenServer GenEvent init function
  lib/Control/Behaviour/GenEvent.erl
  lib/Control/Behaviour/GenEvent.hm
  lib/Control/Behaviour/GenEvent/Proxy.erl
  lib/Control/Behaviour/GenEvent/Types.hm
  lib/Control/Behaviour/GenServer.erl
  lib/Control/Behaviour/GenServer.hm
  lib/Control/Behaviour/GenServer/Proxy.erl
  lib/Control/Behaviour/GenServer/Types.hm
  lib/Foreign/Curry.erl
Labels: enhancement

#271 fix(Term): rename 'size' to 'count'
  lib/Data/Term/Persistent.hm
Labels: enhancement

#272 fix(Term): rename 'size' to 'count'
  lib/Data/Term/Persistent.hm
Labels: enhancement

#275 fix(Process) fix some bugs
  lib/Control/Monad.erl
  lib/Control/Process.erl
  lib/Control/Process.hm
Labels: enhancement

#276 feat(Supervisor): implement the Supervisor behaviour
  lib/Control/Behaviour/Supervisor.erl
  lib/Control/Behaviour/Supervisor.hm
  lib/Control/Behaviour/Supervisor/Proxy.erl
  lib/Control/Behaviour/Supervisor/Proxy.hm
  lib/Control/Behaviour/Supervisor/Types.hm
Labels: enhancement

#277 feat(Port): add 'linkPort', 'unlinkPort' funcs
  lib/Control/Distributed/Port.erl
  lib/Control/Distributed/Port.hm
Labels: enhancement

#282 refactor(Application): make 'Application' an alias of 'String'
  lib/Control/Application.erl
  lib/Control/Application.hm
  lib/Control/Application/Types.hm
Labels: enhancement

#283 fix(ETS): remove the 'decentralizedCounters' option
  lib/Database/ETS.erl
  lib/Database/ETS.hm
Labels: enhancement

#284 feat(PG): introducing PG from Erlang/OTP
  lib/Control/Distributed/PG.erl
  lib/Control/Distributed/PG.hm
Labels: enhancement

#285 feat(Global): introducing Global module from Erlang/OTP
  lib/Control/Distributed/Global.erl
  lib/Control/Distributed/Global.hm
Labels: enhancement

#288 feat(Slave): introducing Slave module from Erlang/OTP
  lib/Control/Distributed/Slave.erl
  lib/Control/Distributed/Slave.hm
Labels: enhancement

#290 build(stack): upgrade lib 'purescript'
  stack.yaml
Labels: enhancement

#291 fix(Supervisor): fix the 'startSupWith' function
  lib/Control/Application/Callback.erl
  lib/Control/Behaviour/Supervisor.erl
  lib/Control/Behaviour/Supervisor.hm
Labels: bug

#292 fix(Node): export 'nodesOf' function
  lib/Control/Distributed/Node.hm
Labels: bug

#293 fix(Mnesia): wrongly parsed TableType
  lib/Database/Mnesia.erl
Labels: enhancement

#294 feat(Port): introducing Port from Erlang/OTP
  lib/Control/Distributed/Port.erl
  lib/Control/Distributed/Port.hm
Labels: enhancement

#297 feat(File): add Dir, File and FilePath modules
  lib/System/Dir.erl
  lib/System/Dir.hm
  lib/System/File.erl
  lib/System/File.hm
  lib/System/FilePath.erl
  lib/System/FilePath.hm
  lib/System/IO.erl
  lib/System/IO.hm
  lib/System/IO/Types.hm
Labels: feature

#299 feat(File): improve the IO and File modules
  lib/System/File.erl
  lib/System/File.hm
  lib/System/IO.erl
  lib/System/IO.hm
  lib/System/IO/Types.hm
Labels: enhancement

#300 fix(Curry): fix the curry function
  lib/Control/Behaviour/GenEvent/Proxy.erl
  lib/Control/Behaviour/GenServer/Proxy.erl
  lib/Foreign/Curry.erl
  lib/Foreign/ToErl.erl
Labels: bug, enhancement

#303 feat(Network): introduce a new design for network lib
  lib/Control/Distributed/NetAdm.hm
  lib/Control/Distributed/Slave.hm
  lib/Network/DTLS.erl
  lib/Network/DTLS.hm
  lib/Network/Inet.erl
  lib/Network/Inet.hm
  lib/Network/Socket.erl
  lib/Network/Socket.hm
  lib/Network/TCP.hm
  lib/Network/TLS.erl
  lib/Network/TLS.hm
  lib/Network/UDP.erl
  lib/Network/UDP.hm
Labels: enhancement, feature

#308 feat(DETS): add more functions to DETS.hm
  lib/Database/DETS.erl
  lib/Database/DETS.hm
Labels: enhancement

#305 feat(Data): add OrdDict and OrdSets for Data
  lib/Data/OrdDict.erl
  lib/Data/OrdDict.hm
  lib/Data/OrdSets.erl
  lib/Data/OrdSets.hm
Labels: enhancement

#302 Add some operator for Binary
  lib/Data/Binary.hm
Labels: enhancement

#313 feat(Process): improve the Process module
  lib/Control/Process.erl
  lib/Control/Process.hm
  lib/Control/Process/Dict.erl
  lib/Control/Process/Dict.hm
  lib/Control/Process/Flags.hm
  lib/Control/Process/Spawn.hm
  lib/Control/Process/Types.hm
  lib/System/VM.hm
Labels: enhancement

#315 fix(Application): changed the callbacks
  lib/Control/Application/Callback.erl
Labels: enhancement

#316 feat(GenStatem): improve the typecass of GenStatem behaviour
  lib/Control/Behaviour/GenStatem.erl
  lib/Control/Behaviour/GenStatem.hm
  lib/Control/Behaviour/GenStatem/Proxy.erl
  lib/Control/Behaviour/GenStatem/Proxy.hm
  lib/Control/Behaviour/GenStatem/Types.hm
Labels: enhancement

#317 fix(Behaviour): fix the wrong arguments
  lib/Control/Behaviour/GenServer.erl
  lib/Control/Behaviour/GenStatem.erl
Labels: enhancement

#322 fix(GenStatem): improve the GenStatem behaviour
  lib/Control/Behaviour/GenEvent/Proxy.hm
  lib/Control/Behaviour/GenServer/Proxy.hm
  lib/Control/Behaviour/GenStatem.hm
  lib/Control/Behaviour/GenStatem/Proxy.erl
  lib/Control/Behaviour/GenStatem/Proxy.hm
  lib/Control/Behaviour/GenStatem/Types.hm
  lib/Control/Behaviour/Supervisor/Proxy.hm
Labels: enhancement

#321 check for functions with duplicate names
  lib/System/Init.hm
  src/Language/Hamler/CodeGen.hs
  stack.yaml
Labels: enhancement

#323 feat(Behaviour): improve the APIs of behaviour
  lib/Control/Behaviour/GenEvent.erl
  lib/Control/Behaviour/GenEvent.hm
  lib/Control/Behaviour/GenEvent/Types.hm
  lib/Control/Behaviour/GenServer.erl
  lib/Control/Behaviour/GenServer.hm
  lib/Control/Behaviour/GenServer/Proxy.erl
  lib/Control/Behaviour/GenServer/Proxy.hm
  lib/Control/Behaviour/GenServer/Types.hm
  lib/Control/Behaviour/GenStatem.hm
  lib/Control/Behaviour/GenStatem/Proxy.erl
  lib/Control/Behaviour/GenStatem/Types.hm
Labels: enhancement

#324 docs: update readme
  README.md
  deploy/packages/deb/debian/control
Labels: enhancement

#327 refactor(Behaviour): refactor the behaviour modules
  lib/Control/Application.erl
  lib/Control/Application.hm
  lib/Control/Application/Callback.erl
  lib/Control/Application/Config.hm
  lib/Control/Application/Resource.hm
  lib/Control/Application/Types.hm
  lib/Control/Behaviour/GenEvent.erl
  lib/Control/Behaviour/GenEvent.hm
  lib/Control/Behaviour/GenEvent/Proxy.erl
  lib/Control/Behaviour/GenServer.erl
  lib/Control/Behaviour/GenServer.hm
  lib/Control/Behaviour/GenServer/Proxy.erl
  lib/Control/Behaviour/GenServer/Types.hm
  lib/Control/Behaviour/GenStatem.erl
  lib/Control/Behaviour/GenStatem.hm
  lib/Control/Behaviour/GenTypes.hm
  lib/Control/Behaviour/Supervisor.erl
  lib/Control/Behaviour/Supervisor.hm
  lib/Control/Behaviour/Supervisor/Proxy.erl
  lib/Control/Behaviour/Supervisor/Proxy.hm
  lib/Control/Behaviour/Supervisor/Types.hm
Labels: enhancement

#329 fix(String): hasPrefix and hasSuffix
  lib/Data/String.erl
Labels: enhancement

#331 fix(Process): add 'processMsgs' function
  lib/Control/Process.hm
  lib/Control/Process/Infos.erl
  lib/Control/Process/Infos.hm
Labels: enhancement

#332 fix(Process): remove 'recv', 'receiveAfter' functions
  lib/Control/Process.erl
  lib/Control/Process.hm
  lib/Prelude.hm
Labels: enhancement

#335 refactor(Foreign): include Foreign/Maybe.hrl in Foreign.hrl
  lib/Control/Application.erl
  lib/Control/Behaviour/GenServer.erl
  lib/Control/Behaviour/GenServer/Proxy.erl
  lib/Control/Behaviour/Supervisor.erl
  lib/Control/Distributed/Node.erl
  lib/Control/Distributed/Port.erl
  lib/Control/Distributed/RPC.erl
  lib/Control/Process/Dict.erl
  lib/Foreign.hrl
  lib/System/OS.erl
  lib/System/VM.erl
Labels: enhancement

#336 feat(Test): add Test module
  .gitignore
  Makefile
  app/Compile.hs
  app/Main.hs
  lib/Data/Binary.hm
  lib/Data/Bool.hm
  lib/Data/Map.hm
  lib/Prelude.hm
  lib/Test/QuickCheck.erl
  lib/Test/QuickCheck.hm
  tests/Test.hm
  tests/Test/Data/Binary.hm
  tests/Test/Data/Map.hm
  tests/Test/Data/String.hm
Labels: enhancement, feature

#330 fix(README): add link to roadmap
  README.md
Labels: Documentation
