Repository hamler-lang/hamler, pull requests merged in 2020-06, with the labels that each got.

#174 docs(README): update the 'Features' and 'Design' block
  README.md
Labels: enhancement

#177 docs(CHANGELOG): add change logs for 0.1.x
  CHANGELOG.md
Labels: enhancement

#179 feat(repl): allow hamler repl command in any folder
  app/Compile.hs
  app/Minteractive.hs
  app/REPL.hs
  stack.yaml
Labels: enhancement

#180 fix(Actions): fix erlang23 compilation bug
  src/Language/Hamler/Make/Actions.hs
Labels: enhancement

#184 feat(package): change version from 0.1 to 0.1.1
  hamler.cabal
  package.yaml
Labels: enhancement

#191 fix(Data.List): fix the 'filter' FFI
  lib/Data/List.hm
Labels: bug

#192 feat(package): bump version to 0.1.2
  package.yaml
Labels: enhancement

#197 fix(Env): fix some build errors in macOS 10.15.5
  Env
  Makefile
Labels: bug

#202 fix(REPL): fix bug of file path stitching error, update stack.yaml
  app/REPL.hs
  stack.yaml
Labels: bug

#206 feat(Bool): define 'otherwise' as a keyword and replace it with 'true'
  lib/Data/Bool.hm
  lib/Prelude.hm
  stack.yaml
Labels: enhancement

#207 docs(README): update 'Documentation' block
  README.md
Labels: Documentation

#209 docs(Changelog): remove the Changelog.md
  CHANGELOG.md
Labels: Documentation

#210 feat(CodeGen): support for tuple with no length limit
  src/Language/Hamler/CodeGen.hs
  stack.yaml
Labels: enhancement

#215 refactor(lib): remove lib/README.md
  lib/README.md
Labels: Documentation

#216 fix(Action): fix there are multiple module_info functions
  src/Language/Hamler/Make/Actions.hs
Labels: enhancement

#217 build: add task 'make clean'
  Makefile
Labels: enhancement

#218 feat(lib): add 'self' function, and improve 'Control.Process' module
  lib/Control/Process.hm
  lib/Prelude.hm
Labels: enhancement

#224 feat(lib): An experimental design for OTP behaviours
  lib/Control/Applicative.erl
  lib/Control/Applicative.hm
  lib/Control/Behaviour/Application.erl
  lib/Control/Behaviour/Application.hm
  lib/Control/Behaviour/Application/Types.hm
  lib/Control/Behaviour/GenEvent.erl
  lib/Control/Behaviour/GenEvent.hm
  lib/Control/Behaviour/GenEvent/Behaviour.erl
  lib/Control/Behaviour/GenEvent/Behaviour.hm
  lib/Control/Behaviour/GenEvent/Types.hm
  lib/Control/Behaviour/GenServer.erl
  lib/Control/Behaviour/GenServer.hm
  lib/Control/Behaviour/GenServer/Client.erl
  lib/Control/Behaviour/GenServer/Client.hm
  lib/Control/Behaviour/GenServer/Proxy.erl
  lib/Control/Behaviour/GenServer/Proxy.hm
  lib/Control/Behaviour/GenServer/Types.hm
  lib/Control/Behaviour/GenStatem.erl
  lib/Control/Behaviour/GenStatem.hm
  lib/Control/Behaviour/GenStatem/Client.erl
  lib/Control/Behaviour/GenStatem/Client.hm
  lib/Control/Behaviour/GenStatem/Proxy.erl
  lib/Control/Behaviour/GenStatem/Proxy.hm
  lib/Control/Behaviour/GenStatem/Types.hm
  lib/Control/Behaviour/Supervisor.erl
  lib/Control/Behaviour/Supervisor.hm
  lib/Control/Behaviour/Supervisor/Behaviour.erl
  lib/Control/Behaviour/Supervisor/Behaviour.hm
  lib/Control/Behaviour/Supervisor/Types.hm
  lib/Control/Monad.erl
  lib/Control/Monad.hm
  lib/Control/OTP/GenEvent/Types.hm
  lib/Control/OTP/GenServer.erl
  lib/Control/OTP/GenServer.hm
  lib/Control/OTP/GenServer/Behaviour.erl
  lib/Control/OTP/GenServer/Behaviour.hm
  lib/Control/OTP/GenStatem/Types.hm
  lib/Control/Process.erl
  lib/Control/Process.hm
  lib/Control/Process/Types.hm
  lib/Data/Either.hm
  lib/Data/Maybe.hm
  lib/Data/Result.hm
  lib/Data/Traversable.hm
  lib/Demo/GenServer.hm
  lib/Prelude.hm
  lib/System/Error.hm
Labels: enhancement

#226 refactor(lib): format System.IO modules
  lib/System/IO.erl
  lib/System/IO.hm
  lib/System/IO/Printf.erl
  lib/System/IO/Printf.hm
Labels: enhancement

#227 feat(lib): Improve the GenServer behaviour
  lib/Control/Behaviour/Application/Types.hm
  lib/Control/Behaviour/GenEvent.erl
  lib/Control/Behaviour/GenEvent/Proxy.erl
  lib/Control/Behaviour/GenEvent/Proxy.hm
  lib/Control/Behaviour/GenServer.erl
  lib/Control/Behaviour/GenServer.hm
  lib/Control/Behaviour/GenServer/Proxy.erl
  lib/Control/Behaviour/GenServer/Proxy.hm
  lib/Control/Behaviour/GenServer/Types.hm
  lib/Control/Behaviour/Supervisor.erl
  lib/Control/Behaviour/Supervisor/Proxy.erl
  lib/Control/Behaviour/Supervisor/Proxy.hm
  lib/Control/Process.hm
  lib/DemoServer.hm
  lib/ERTS/Application.erl
  lib/ERTS/Application.hm
Labels: enhancement

#231 refactor(lib): move Application to Kernel, and imporve Behaviours
  lib/Control/Behaviour/GenServer.erl
  lib/Control/Behaviour/GenServer.hm
  lib/Control/Behaviour/GenServer/Client.erl
  lib/Control/Behaviour/GenServer/Client.hm
  lib/Control/Behaviour/GenStatem.erl
  lib/Control/Behaviour/GenStatem.hm
  lib/Control/Behaviour/GenStatem/Client.erl
  lib/Control/Behaviour/GenStatem/Client.hm
  lib/DemoServer.hm
  lib/Kernel/Application.erl
  lib/Kernel/Application.hm
Labels: enhancement

#232 feat(GenServer): add LifeCircle class
  lib/Control/Behaviour/GenServer.hm
  lib/Control/Behaviour/GenServer/Proxy.erl
  lib/DemoServer.hm
Labels: enhancement

#233 feat(GenServer): improve types and APIs of GenServer behaviour
  lib/Control/Behaviour/GenServer.erl
  lib/Control/Behaviour/GenServer.hm
  lib/Control/Behaviour/GenServer/Types.hm
  lib/DemoServer.hm
Labels: enhancement
