Repository hamler-lang/hamler, pull requests merged in 2020-08, with the labels that each got.

#339 refactor(Process): remove 'self' function
  lib/Control/Process.hm
  lib/Prelude.hm
Labels: Refator

#340 feat(CodeGen): add new receive syntex
  src/Language/Hamler/CodeGen.hs
  src/Language/Hamler/Util.hs
  stack.yaml
Labels: enhancement

#342 fix(Process): refactor the send, exit functions
  lib/Control/Process.erl
  lib/Control/Process.hm
  lib/Control/Process/Spawn.hm
  lib/Prelude.hm
Labels: Refator, enhancement

#343 fix(Process): remove 'exitWith', 'exitProcWith' functions
  lib/Control/Process.erl
  lib/Control/Process.hm
Labels: enhancement

#341 fix(Map): fix some Map functions
  lib/Data/Map.erl
  lib/Data/Map.hm
  lib/Test/QuickCheck.hm
  tests/Test/Data/Map.hm
Labels: bug, enhancement

#345 fix(stack.yaml): fix 'receive' layout bug
  stack.yaml
Labels: bug

#346 refactor(lib): refactor QuickCheck and FFI module
  lib/Test/QuickCheck.erl
  lib/Test/QuickCheck.hm
Labels: enhancement

#347 fix(CodeGen): fix 'receive' funciton bug
  src/Language/Hamler/CodeGen.hs
  src/Language/Hamler/Util.hs
Labels: enhancement

#348 Bump version to 0.2
  hamler.cabal
  package.yaml
Labels: enhancement

#352 refactor(Process): rename 'selfPid' to 'getSelf'
  lib/Control/Process.hm
  lib/Prelude.hm
Labels: enhancement

#354 fix(CodeGen): fix receive var name
  src/Language/Hamler/Util.hs
Labels: bug

#362 feat(CodeGen): change Binary pattern match syntax
  src/Language/Hamler/CodeGen.hs
  stack.yaml
Labels: enhancement

#359 Add typeclass for data structure
  lib/Data/Array.hm
  lib/Data/Digraph.erl
  lib/Data/Digraph.hm
  lib/Data/Either.hm
  lib/Data/Map.hm
  lib/Data/Ord.hm
  lib/Data/OrdDict.hm
  lib/Data/OrdSets.hm
  lib/Data/Queue.hm
  lib/Data/Result.hm
  lib/Data/Set.hm
  lib/Data/Show.hm
  lib/Data/Timeout.hm
  lib/Data/Unit.hm
Labels: enhancement

#370 feat(printf): add printf doc
  lib/System/IO/Printf.hm
Labels: enhancement

#367 feat(Error): add try, catch, catchException functions
  lib/Prelude.hm
  lib/System/Error.erl
  lib/System/Error.hm
  lib/Test/QuickCheck.hm
  src/Language/Hamler/CodeGen.hs
  src/Language/Hamler/Util.hs
Labels: enhancement

#393 test(Env, File, Process): add some test functions
  lib/System/Env.hm
  tests/Test.hm
  tests/Test/Control/Process.hm
  tests/Test/Data/Bits.hm
  tests/Test/Data/Set.hm
  tests/Test/System/Dir.hm
  tests/Test/System/Env.hm
  tests/Test/System/File.hm
Labels: test
